apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: test-abc
  name: maven-test
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    k8s-app: test-abc
  type: NodePort


---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: maven
  labels:
    k8s-app: test-abc
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: test-abc
  template:
    metadata:
      labels:
        k8s-app: test-abc
    spec:
      containers:
      - name: maven
        image: 10.100.26.151:5000/maven:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: maven-qwe
spec:
  rules:
  - host: maven.com
    http:
      paths:
      - backend:
          serviceName: maven-test
          servicePort: 8080
